### ISSUE TITLE
When you open the second file with asyncomplete-gocode, 'PANIC PANIC PANIC' will be displayed.

### ISSUE THREAD

**Issue by maamo888** [prabirshrestha/asyncomplete-gocode.vim#6]
(I'm sorry for my poor English.)

Hi, prabirshrestha

First of all, I appreciate vim-lsp, asyncomplete and related great plugins.

When you open the second file with asyncomplete-gocode, `PANIC PANIC PANIC` will be displayed.

## file tree

```
sample$ tree
.
├── main.go
└── util.go
```

## 1: main.go

<img width="1017" alt="main go" src="https://user-images.githubusercontent.com/14961986/45439151-02336c00-b6f4-11e8-961d-abb898e02dc3.png">

## 2: util.go

<img width="1017" alt="util go" src="https://user-images.githubusercontent.com/14961986/45439160-0790b680-b6f4-11e8-894a-dace3e516a51.png">

**Comment by prabirshrestha** [comment]
Can you upload the log file. Instructions can be found at readme.md in asyncomplete blog.

**Comment by maamo888** [comment]
## Additional information.

* Vim
    * version 8.1.366
* Version
    * go version go1.11 darwin/amd64
* gocode
    * https://github.com/mdempsky/gocode

I tried using `completor.vim` but it does not seem to be a problem.

**Comment by maamo888** [comment]
same issue.

https://github.com/sourcegraph/go-langserver/issues/317

It seems that it was modified by `master` of go-langserver.

I will use LSP.

**go-langserver on vim-lsp setting**

```vim
if executable('go-langserver')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'go-langserver',
        \ 'cmd': {server_info->['go-langserver', '-gocodecompletion']},
        \ 'whitelist': ['go'],
        \ })
endif
```
