### ISSUE TITLE
Some completion suggestions are missing for structs

### ISSUE THREAD

**Issue by idanko** [prabirshrestha/asyncomplete-gocode.vim#7]
Hi. I use the recent gocode for by [mdempsky/gocode](https://github.com/mdempsky/gocode) and found that the last field is missing in the pop-up menu.

![screen](https://user-images.githubusercontent.com/8293386/49935475-c7e78f80-fed9-11e8-9140-e17388ab5a63.jpg)

Debugging a bit I have noticed that arguments are passed to the gocode are correct.

init.vim:
```
call asyncomplete#register_source(asyncomplete#sources#gocode#get_source_options({
    \ 'name': 'gocode',
    \ 'whitelist': ['go'],
    \ 'completor': function('asyncomplete#sources#gocode#completor'),
    \ 'config': {
    \    'gocode_path': expand('~/Go/bin/gocode')
    \  },
    \ }))
```

**Comment by idanko** [comment]
Update: the workaround is `let g:asyncomplete_smart_completion = 0`. Just curious why is the smart completion truncating the last suggesting candidate? :)

**Comment by prabirshrestha** [comment]
This is now fixed by https://github.com/prabirshrestha/asyncomplete.vim/pull/95. Please try updating to latest asyncomplete.vim and enable re-enable smart completion.
